"""add correct_answer to TestResult

Revision ID: 1c3cca2707a2
Revises: d78c2e9f21d7
Create Date: 2025-06-12 21:52:09.128605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3cca2707a2'
down_revision = 'd78c2e9f21d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_result', sa.Column('correct_answer', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_result', 'correct_answer')
    # ### end Alembic commands ###
