"""add support for open questions in TestResult

Revision ID: 295ce02943bf
Revises: d6ac9b5a5f79
Create Date: 2025-08-04 14:22:04.769796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295ce02943bf'
down_revision = 'd6ac9b5a5f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_result', 'correct_answer',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('test_result', 'selected_answer',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('test_result', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_result', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('test_result', 'selected_answer',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('test_result', 'correct_answer',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###
