"""add step to TestResult

Revision ID: a5e2575ae220
Revises: 49376b12b0b4
Create Date: 2025-07-08 17:02:38.866242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e2575ae220'
down_revision = '49376b12b0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_result', sa.Column('step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_result', 'step')
    # ### end Alembic commands ###
