"""add department to onboarding_template

Revision ID: c4a5cb293b26
Revises: 295ce02943bf
Create Date: 2026-03-05 12:34:37.404684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a5cb293b26'
down_revision = '295ce02943bf'
branch_labels = None
depends_on = None


def upgrade():
    # Добавляем колонку с server_default, чтобы существующие строки не упали на NOT NULL
    op.add_column(
        'onboarding_template',
        sa.Column('department', sa.String(length=150), nullable=False, server_default='product')
    )

    op.create_index(op.f('ix_onboarding_template_department'), 'onboarding_template', ['department'], unique=False)

    # (опционально) убираем дефолт на уровне БД после заполнения существующих записей
    op.alter_column('onboarding_template', 'department', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_template_department'), table_name='onboarding_template')
    op.drop_column('onboarding_template', 'department')
    # ### end Alembic commands ###
