"""Ensure onboarding_step fields exist

Revision ID: d6ac9b5a5f79
Revises: a5e2575ae220
Create Date: 2025-07-11 13:22:15.068157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ac9b5a5f79'
down_revision = 'a5e2575ae220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
